// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUGWaI81mF6kA2jet4PHe6aKldeCv6hEY',
    appId: '1:312547582263:web:aa42b963c279a2e5563ab2',
    messagingSenderId: '312547582263',
    projectId: 'ask-ai-3321c',
    authDomain: 'ask-ai-3321c.firebaseapp.com',
    storageBucket: 'ask-ai-3321c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgcopEKvX_sEi0KtVeOWshcTooMFKr7L8',
    appId: '1:312547582263:android:8c10cbacb563ab37563ab2',
    messagingSenderId: '312547582263',
    projectId: 'ask-ai-3321c',
    storageBucket: 'ask-ai-3321c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPtu6BXrp9FZ1ifoPGtIMOcvQXnuKS0F0',
    appId: '1:312547582263:ios:aef3ba51cbb74b4a563ab2',
    messagingSenderId: '312547582263',
    projectId: 'ask-ai-3321c',
    storageBucket: 'ask-ai-3321c.firebasestorage.app',
    androidClientId: '312547582263-838c1gvnqcdcngqctk56o0h41fdji6ua.apps.googleusercontent.com',
    iosClientId: '312547582263-spe88vrjrmdpvs7oriolrlcec9rkkhbt.apps.googleusercontent.com',
    iosBundleId: 'com.example.aiChatbot',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCPtu6BXrp9FZ1ifoPGtIMOcvQXnuKS0F0',
    appId: '1:312547582263:ios:aef3ba51cbb74b4a563ab2',
    messagingSenderId: '312547582263',
    projectId: 'ask-ai-3321c',
    storageBucket: 'ask-ai-3321c.firebasestorage.app',
    androidClientId: '312547582263-838c1gvnqcdcngqctk56o0h41fdji6ua.apps.googleusercontent.com',
    iosClientId: '312547582263-spe88vrjrmdpvs7oriolrlcec9rkkhbt.apps.googleusercontent.com',
    iosBundleId: 'com.example.aiChatbot',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCUGWaI81mF6kA2jet4PHe6aKldeCv6hEY',
    appId: '1:312547582263:web:f720993fc4db5d5b563ab2',
    messagingSenderId: '312547582263',
    projectId: 'ask-ai-3321c',
    authDomain: 'ask-ai-3321c.firebaseapp.com',
    storageBucket: 'ask-ai-3321c.firebasestorage.app',
  );
}
